stages:
  - pull

variables:
  GITLAB_CLONE_DIR: "cloudflaredns-java"

pull_source:
  stage: pull
  script:
    - echo "Cloning GitHub repository..."
    - git clone --depth 1 https://oauth2:${GITHUB_PERSONAL_ACCESS_TOKEN}@github.com/th-schwarz/CloudflareDNS-java.git ${GITLAB_CLONE_DIR}
    - echo "Repository cloned successfully."
  only:
    - schedules
