
when:
  - event: push
    branch: develop

steps:
    - name: hello
      image: alpine
      commands:
        - echo "Hello World!"

    - name: sonarcloud-scan
      image: maven:3-amazoncorretto-17-alpine
      environment:
        SONAR_TOKEN:
          from_secret: sonar_token
      commands:
        - mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=th-schwarz_CloudflareDNS-java -Dsonar.token=$SONAR_TOKEN