
when:
  - event: push
    branch: develop

steps:
    - name: hello
      image: alpine
      commands:
        - echo "Hello World!"

    - name: checkout
      image: maven:3-amazoncorretto-17-alpine
      commands:
        - git clone $CI_REPO_URL .
        - git checkout $CI_COMMIT_SHA

    - name: compile
      image: maven:3-amazoncorretto-17-alpine
      commands:
        - mvn clean compile



