name: CI Pipeline

on:
  push:
    branches:
      - develop
      - 'feature**'
  pull_request:
    branches:
      - develop
  create:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maven:3-amazoncorretto-17-alpine

    steps:
      - name: Build with Maven
        run: |
          echo "Running package..."
          mvn clean package
