name: Build and Analyse

on:
  push:
    branches:
      - develop
      - feature*
  pull_request:
    types: [ opened, synchronize, reopened ]

defaults:
  run:
    shell: bash

jobs:

  build-and-analyse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Setup Java and Maven
        uses: ./.github/actions/setup-java-maven

      - name: Build and test
        run: mvn -B verify

      - name: Publish Test Report
        uses: ./.github/actions/publish-report/
        if: ${{ always() }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          report-name: Summary of JUnit Tests
