name: Build and Test

on:
  push:
    branches:
      - develop
      - feature*
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:

  mvn-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Cache maven repository
        uses: actions/cache@v4.2.0
        with:
          path: ~/.m2/repository
          key: maven
          restore-keys: maven
      - name: Build with Maven and Test
        env:
          API_EMAIL: ${{ secrets.API_EMAIL }}
          API_KEY: ${{ secrets.API_KEY }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: mvn clean test
