name: Clone GitLab Repository Daily

# Schedule the workflow to run daily at midnight
on:
  schedule:
    - cron: '0 0 * * *' # Adjust the cron schedule as required (UTC)

jobs:
  clone-gitlab-repo:
    name: Clone GitLab Repository
    runs-on: ubuntu-latest

    steps:
      - name: Clone GitLab repository
        env:
          # Set the GitLab access token in GitHub secrets as `GITLAB_TOKEN`
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          # Authenticate using GitLab token
          git clone https://gitlab-ci-token:${GITLAB_TOKEN}@thischwa/CloudflareDNS-java.git cloned-repo
